[build]
command = "pip install -r requirements.txt"  # Установка зависимостей
functions = "functions"                      # Папка с функциями
publish = "public"                           # Папка со статикой
